/**
 * Generated by "@vuepress/internal-routes"
 */

import { injectComponentOption, ensureAsyncComponentsLoaded } from '@app/util'
import rootMixins from '@internal/root-mixins'
import GlobalLayout from "/Users/tom.bunn/Documents/repositories/act-docs/node_modules/@vuepress/core/lib/client/components/GlobalLayout.vue"

injectComponentOption(GlobalLayout, 'mixins', rootMixins)
export const routes = [
  {
    name: "v-44e31da2",
    path: "/developer_docs/3_developer_docs/1_more_developer_docs.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-44e31da2").then(next)
    },
  },
  {
    name: "v-2f8ecd75",
    path: "/developer_docs/3_developer_docs/0_developer_docs.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-2f8ecd75").then(next)
    },
  },
  {
    name: "v-20cd36cf",
    path: "/getting_started/1_more_docs/0_more_docs.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-20cd36cf").then(next)
    },
  },
  {
    name: "v-1ec03e6e",
    path: "/getting_started/0_getting_started/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-1ec03e6e").then(next)
    },
  },
  {
    path: "/getting_started/0_getting_started/index.html",
    redirect: "/getting_started/0_getting_started/"
  },
  {
    name: "v-39fb820f",
    path: "/getting_started/0_getting_started/1_FAQ.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-39fb820f").then(next)
    },
  },
  {
    name: "v-af0a1ab0",
    path: "/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-af0a1ab0").then(next)
    },
  },
  {
    path: "/index.html",
    redirect: "/"
  },
  {
    path: '*',
    component: GlobalLayout
  }
]