/**
 * Generated by "@vuepress/internal-routes"
 */

import { injectComponentOption, ensureAsyncComponentsLoaded } from '@app/util'
import rootMixins from '@internal/root-mixins'
import GlobalLayout from "/Users/tom.bunn/Documents/repositories/act-docs/node_modules/@vuepress/core/lib/client/components/GlobalLayout.vue"

injectComponentOption(GlobalLayout, 'mixins', rootMixins)
export const routes = [
  {
    name: "v-39fb820f",
    path: "/getting_started/0_getting_started/1_FAQ.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-39fb820f").then(next)
    },
  },
  {
    name: "v-1ec03e6e",
    path: "/getting_started/0_getting_started/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-1ec03e6e").then(next)
    },
  },
  {
    path: "/getting_started/0_getting_started/index.html",
    redirect: "/getting_started/0_getting_started/"
  },
  {
    name: "v-af0a1ab0",
    path: "/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-af0a1ab0").then(next)
    },
  },
  {
    path: "/index.html",
    redirect: "/"
  },
  {
    name: "v-364b4b22",
    path: "/release_notes/0_release_notes/0_general.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-364b4b22").then(next)
    },
  },
  {
    name: "v-20cd36cf",
    path: "/getting_started/1_more_docs/0_more_docs.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-20cd36cf").then(next)
    },
  },
  {
    name: "v-d7be7676",
    path: "/release_notes/0_release_notes/1_0.0.1_beta_release.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-d7be7676").then(next)
    },
  },
  {
    name: "v-351405e2",
    path: "/release_notes/1_version_1/0_1.0.0_release.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-351405e2").then(next)
    },
  },
  {
    name: "v-3902ef6b",
    path: "/release_notes/release_template.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-3902ef6b").then(next)
    },
  },
  {
    path: '*',
    component: GlobalLayout
  }
]