/**
 * Generated by "@vuepress/internal-site-data"
 */
export const siteData = {
  "title": "act docs",
  "description": "Documentation for the Usage and setup of AWF workflows",
  "base": "/",
  "headTags": [
    [
      "meta",
      {
        "name": "theme-color",
        "content": "#32A4A0"
      }
    ],
    [
      "meta",
      {
        "name": "apple-mobile-web-app-capable",
        "content": "yes"
      }
    ],
    [
      "meta",
      {
        "name": "apple-mobile-web-app-status-bar-style",
        "content": "black"
      }
    ]
  ],
  "pages": [
    {
      "title": "FAQ",
      "frontmatter": {},
      "regularPath": "/getting_started/0_getting_started/1_FAQ.html",
      "relativePath": "getting_started/0_getting_started/1_FAQ.md",
      "key": "v-39fb820f",
      "path": "/getting_started/0_getting_started/1_FAQ.html"
    },
    {
      "title": "More developer docs",
      "frontmatter": {},
      "regularPath": "/developer_docs/3_developer_docs/1_more_developer_docs.html",
      "relativePath": "developer_docs/3_developer_docs/1_more_developer_docs.md",
      "key": "v-44e31da2",
      "path": "/developer_docs/3_developer_docs/1_more_developer_docs.html"
    },
    {
      "title": "Home",
      "frontmatter": {
        "home": true,
        "heroImage": "/img/logo.svg",
        "tagline": null,
        "actionText": "Quick Start →",
        "actionLink": "/guide/",
        "features": [
          {
            "title": "Feature 1 Title",
            "details": "Feature 1 Description"
          },
          {
            "title": "Feature 2 Title",
            "details": "Feature 2 Description"
          },
          {
            "title": "Feature 3 Title",
            "details": "Feature 3 Description"
          }
        ],
        "footer": "Made by  with ❤️"
      },
      "regularPath": "/",
      "relativePath": "index.md",
      "key": "v-af0a1ab0",
      "path": "/"
    },
    {
      "title": "Developer docs",
      "frontmatter": {},
      "regularPath": "/developer_docs/3_developer_docs/0_developer_docs.html",
      "relativePath": "developer_docs/3_developer_docs/0_developer_docs.md",
      "key": "v-2f8ecd75",
      "path": "/developer_docs/3_developer_docs/0_developer_docs.html",
      "headers": [
        {
          "level": 2,
          "title": "Header2",
          "slug": "header2"
        },
        {
          "level": 3,
          "title": "Header3",
          "slug": "header3"
        }
      ]
    },
    {
      "title": "More docs",
      "frontmatter": {},
      "regularPath": "/getting_started/1_more_docs/0_more_docs.html",
      "relativePath": "getting_started/1_more_docs/0_more_docs.md",
      "key": "v-20cd36cf",
      "path": "/getting_started/1_more_docs/0_more_docs.html"
    },
    {
      "title": "Vuepress docs",
      "frontmatter": {},
      "regularPath": "/getting_started/0_getting_started/",
      "relativePath": "getting_started/0_getting_started/README.md",
      "key": "v-1ec03e6e",
      "path": "/getting_started/0_getting_started/"
    }
  ],
  "themeConfig": {
    "smoothScroll": true,
    "repo": "",
    "editLinks": false,
    "docsDir": "",
    "editLinkText": "",
    "lastUpdated": false,
    "displayAllHeaders": true,
    "nav": [
      {
        "text": "Getting started",
        "link": "/getting_started/0_getting_started/"
      },
      {
        "text": "Developer docs",
        "link": "/developer_docs/3_developer_docs/0_developer_docs"
      },
      {
        "text": "Vuepress",
        "link": "https://v1.vuepress.vuejs.org/"
      }
    ],
    "sidebar": {
      "/getting_started/": [
        {
          "title": "Getting started",
          "collapsable": false,
          "sidebarDepth": 0,
          "children": [
            [
              "0_getting_started/",
              "Getting Started"
            ],
            "0_getting_started/1_FAQ"
          ]
        },
        {
          "title": "More docs",
          "collapsable": false,
          "sidebarDepth": 0,
          "children": [
            "1_more_docs/0_more_docs"
          ]
        }
      ],
      "/developer_docs/": [
        {
          "title": "Developer docs",
          "collapsable": false,
          "sidebarDepth": 0,
          "children": [
            "3_developer_docs/0_developer_docs",
            "3_developer_docs/1_more_developer_docs"
          ]
        }
      ]
    }
  }
}