/**
 * Generated by "@vuepress/internal-site-data"
 */
export const siteData = {
  "title": "act docs",
  "description": "Documentation for the Usage and setup of AWF workflows",
  "base": "/",
  "headTags": [
    [
      "meta",
      {
        "name": "theme-color",
        "content": "#32A4A0"
      }
    ],
    [
      "meta",
      {
        "name": "apple-mobile-web-app-capable",
        "content": "yes"
      }
    ],
    [
      "meta",
      {
        "name": "apple-mobile-web-app-status-bar-style",
        "content": "black"
      }
    ]
  ],
  "pages": [
    {
      "title": "FAQ",
      "frontmatter": {},
      "regularPath": "/getting_started/0_getting_started/1_FAQ.html",
      "relativePath": "getting_started/0_getting_started/1_FAQ.md",
      "key": "v-39fb820f",
      "path": "/getting_started/0_getting_started/1_FAQ.html"
    },
    {
      "title": "Vuepress docs",
      "frontmatter": {},
      "regularPath": "/getting_started/0_getting_started/",
      "relativePath": "getting_started/0_getting_started/README.md",
      "key": "v-1ec03e6e",
      "path": "/getting_started/0_getting_started/"
    },
    {
      "title": "Home",
      "frontmatter": {
        "home": true,
        "heroImage": "/img/logo.svg",
        "tagline": null,
        "actionText": "Quick Start →",
        "actionLink": "/guide/",
        "features": [
          {
            "title": "Feature 1 Title",
            "details": "Feature 1 Description"
          },
          {
            "title": "Feature 2 Title",
            "details": "Feature 2 Description"
          },
          {
            "title": "Feature 3 Title",
            "details": "Feature 3 Description"
          }
        ],
        "footer": "Made by  with ❤️"
      },
      "regularPath": "/",
      "relativePath": "index.md",
      "key": "v-af0a1ab0",
      "path": "/"
    },
    {
      "title": "Release outline",
      "frontmatter": {},
      "regularPath": "/release_notes/0_release_notes/0_general.html",
      "relativePath": "release_notes/0_release_notes/0_general.md",
      "key": "v-364b4b22",
      "path": "/release_notes/0_release_notes/0_general.html"
    },
    {
      "title": "More docs",
      "frontmatter": {},
      "regularPath": "/getting_started/1_more_docs/0_more_docs.html",
      "relativePath": "getting_started/1_more_docs/0_more_docs.md",
      "key": "v-20cd36cf",
      "path": "/getting_started/1_more_docs/0_more_docs.html"
    },
    {
      "title": "0.0.1 (BETA)",
      "frontmatter": {},
      "regularPath": "/release_notes/0_release_notes/1_0.0.1_beta_release.html",
      "relativePath": "release_notes/0_release_notes/1_0.0.1_beta_release.md",
      "key": "v-d7be7676",
      "path": "/release_notes/0_release_notes/1_0.0.1_beta_release.html",
      "headers": [
        {
          "level": 2,
          "title": "👍 New features",
          "slug": "👍-new-features"
        },
        {
          "level": 2,
          "title": "✅ Fixed Issues",
          "slug": "✅-fixed-issues"
        },
        {
          "level": 2,
          "title": "🚀 Improvements",
          "slug": "🚀-improvements"
        },
        {
          "level": 2,
          "title": "🛑 Blockers / known issues",
          "slug": "🛑-blockers-known-issues"
        },
        {
          "level": 2,
          "title": "🗒️ Additional Resources",
          "slug": "🗒️-additional-resources"
        }
      ]
    },
    {
      "title": "1.0.0",
      "frontmatter": {},
      "regularPath": "/release_notes/1_version_1/0_1.0.0_release.html",
      "relativePath": "release_notes/1_version_1/0_1.0.0_release.md",
      "key": "v-351405e2",
      "path": "/release_notes/1_version_1/0_1.0.0_release.html"
    },
    {
      "title": "x.x.x Release",
      "frontmatter": {},
      "regularPath": "/release_notes/release_template.html",
      "relativePath": "release_notes/release_template.md",
      "key": "v-3902ef6b",
      "path": "/release_notes/release_template.html",
      "headers": [
        {
          "level": 3,
          "title": "act | a carbon tool",
          "slug": "act-a-carbon-tool"
        },
        {
          "level": 3,
          "title": "date",
          "slug": "date"
        },
        {
          "level": 2,
          "title": "👍 New features",
          "slug": "👍-new-features"
        },
        {
          "level": 2,
          "title": "✅ Fixed Issues",
          "slug": "✅-fixed-issues"
        },
        {
          "level": 2,
          "title": "🚀 Improvements",
          "slug": "🚀-improvements"
        },
        {
          "level": 2,
          "title": "🗒️ Additional Resources",
          "slug": "🗒️-additional-resources"
        }
      ]
    }
  ],
  "themeConfig": {
    "smoothScroll": true,
    "repo": "",
    "editLinks": false,
    "docsDir": "",
    "editLinkText": "",
    "lastUpdated": false,
    "displayAllHeaders": true,
    "nav": [
      {
        "text": "Getting started",
        "link": "/getting_started/0_getting_started/"
      },
      {
        "text": "Release notes",
        "link": "/release_notes/0_release_notes/0_general"
      }
    ],
    "sidebar": {
      "/getting_started/": [
        {
          "title": "Getting started",
          "collapsable": false,
          "sidebarDepth": 1,
          "children": [
            [
              "0_getting_started/",
              "Getting Started"
            ],
            "0_getting_started/1_FAQ"
          ]
        }
      ],
      "/release_notes/": [
        {
          "title": "Outline",
          "collapsable": false,
          "sidebarDepth": 1,
          "children": [
            "0_release_notes/0_general",
            "0_release_notes/1_0.0.1_beta_release"
          ]
        },
        {
          "title": "Version 1",
          "collapsable": false,
          "sidebarDepth": 1,
          "children": [
            "1_version_1/0_1.0.0_release"
          ]
        }
      ]
    }
  }
}